packages:
  - apps/*
  - packages/*

allowBuilds:
  agent-browser: true
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - agent-browser
  - '@node-rs/argon2'
  - esbuild
  - sharp
  - unrs-resolver
